### ISSUE TITLE
Tags not showing

### ISSUE THREAD

**Issue by dwedigital** [LekoArts/gatsby-themes#255] opened 2020-01-27 20:21 UTC
## Description

I have created a post with the following frontmatter:

```
---
title: Adding Google Tag Manager to a React App
date: 2020-01-22 09:00
description: Easily implement Google Tag Manager within a React app using multiple environments
banner: ./gtm.png
tags:
    - React
    - Analytics
    - Google Tag Manager
---
```

### Expected result

I then expect the tags in the front matter to appear within the `/tags` page but it only still shows the following:

Dark Arts (2)
Novel (1)
Tutorial (2)

### Actual result

What happened.

### Environment

  System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  Languages:
    Python: 3.8.0 - /Users/dave/.pyenv/shims/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.2
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.13.3 => 2.19.5 
    gatsby-plugin-google-analytics: ^2.1.4 => 2.1.34 
    gatsby-plugin-manifest: ^2.2.3 => 2.2.38 
    gatsby-plugin-netlify: ^2.1.3 => 2.1.31 
    gatsby-plugin-offline: ^2.2.4 => 2.2.10 
    gatsby-plugin-sitemap: ^2.2.19 => 2.2.26 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.8 => 1.1.8 
  npmGlobalPackages:
    gatsby-cli: 2.8.27

**Comment by LekoArts** [comment] 2020-02-29 10:57
Hi, thanks for the issue!

I spun up the example site, added some other tags to one of the posts and looked at `/tags`. They appear there:

![image](https://user-images.githubusercontent.com/16143594/75606175-80ebb700-5aea-11ea-9893-03c2b8e611b0.png)

Hence I can't reproduce your problem with the given steps. Maybe try a `gatsby clean` or make sure that the indentation/format of your frontmatter is correct. I'll close this issue as answered but feel free to comment if you need further assistance. Thanks!

**Closed by LekoArts** 2020-02-29 10:57 UTC
Labels: type: bug
