### ISSUE TITLE
[minimal-blog]: Issue with sharp@0.27.X dependency on Apple M1s

### ISSUE THREAD

**Issue by rodgracas** [LekoArts/gatsby-themes#594] opened 2021-05-30 18:25 UTC
## Description

I'm having some issues when running `npm i @lekoarts/gatsby-theme-minimal-blog` on Apple M1. This is due to the `sharp` dependency `0.27.X` (see [#2460](https://github.com/lovell/sharp/issues/2460)).

The dependencies bump would probably fix it, as opened in this [pull request](https://github.com/LekoArts/gatsby-themes/pull/587), since it updates both `gatsby-transformer-sharp` and `gatsby-plugin-sharp` to use sharp **v0.28**. I added a comment on that pull request, but decided to open an issue to give more visibility since the CI is failing..

This currently affects minimal-blog theme.

Results from running `npm list sharp`:

```
minimal-blog@1.3.10 /../../
├─┬ UNMET DEPENDENCY @lekoarts/gatsby-theme-minimal-blog@2.7.6
│ └─┬ UNMET DEPENDENCY @lekoarts/gatsby-theme-minimal-blog-core@2.7.6
│   ├─┬ UNMET DEPENDENCY gatsby-plugin-sharp@2.14.1
│   │ └── UNMET DEPENDENCY sharp@0.27.2
│   └─┬ UNMET DEPENDENCY gatsby-transformer-sharp@2.12.0
│     └── UNMET DEPENDENCY sharp@0.27.2
└─┬ UNMET DEPENDENCY gatsby-plugin-manifest@2.12.0
  └── UNMET DEPENDENCY sharp@0.27.2
```

### Steps to reproduce

- On Apple M1, run `npm i @lekoarts/gatsby-theme-minimal-blog`

### Expected result

What should happen?

- Install dependencies should succeed after `gatsby-transformer-sharp` and `gatsby-plugin-sharp` bump to use sharp v0.28.X.

### Actual result

Fails when installing dependencies.

```
> sharp@0.27.2 install ...
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
...
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.5/libvips-8.10.5-darwin-arm64v8.tar.br
ERR! sharp Prebuilt libvips 8.10.5 binaries are not yet available for darwin-arm64v8
...
/usr/local/include/vips/vips8:35:10: fatal error: 'glib-object.h' file not found
#include <glib-object.h>
         ^~~~~~~~~~~~~~~
1 error generated.
```

### Environment

```
  System:
    OS: macOS 11.3.1
    CPU: (8) arm64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.212
    Safari: 14.1
  npmPackages:
    gatsby: ^2.25.3 => 2.32.4
    gatsby-plugin-gatsby-cloud: ^1.0.1 => 1.0.1
    gatsby-plugin-google-analytics: ^2.4.1 => 2.11.0
    gatsby-plugin-netlify: ^2.4.0 => 2.11.0
    gatsby-plugin-offline: ^3.3.3 => 3.10.1
    gatsby-plugin-sitemap: ^2.5.1 => 2.12.0
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.13 => 1.1.20
```

**Comment by emptypockets-dev** [comment] 2021-05-31 23:08
I can confirm I'm having the same issue. This was a bad time to try Gatsby for the first time but at least it looks like a solution is known. Looking forward to digging in more.

**Comment by LekoArts** [comment] 2021-06-01 05:22
Hi, thanks for the issue!

The Pull Request you linked can't simply be merged as it's updating to all new major versions. I'm in the process of doing this manually: https://github.com/LekoArts/gatsby-themes/issues/570

However, you're not blocked by my progress on this issue since you can use yarn resolutions: https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

Add this to your `package.json` and you'll be good:

```json
{
  "resolutions": {
    "sharp": "^0.28"
  }
}
```

**Closed by LekoArts** 2021-06-01 05:22 UTC
Labels: type: bug

**Comment by rodgracas** [comment] 2021-06-01 09:09
Thanks! That did the trick 💯
